# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipe < Formula
  desc "CI-friendly pipeline runner inspired by Taskfile"
  homepage "https://github.com/idestis/pipe"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/idestis/pipe/releases/download/v1.0.3/pipe-1.0.3-darwin-amd64.tar.gz"
      sha256 "eb75a5eba2f2b992d01dea3abbe4c26ea667c6abb575023cd6d83b5582aa2f2e"

      def install
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/idestis/pipe/releases/download/v1.0.3/pipe-1.0.3-darwin-arm64.tar.gz"
      sha256 "66887851db234d668e89c8fafa771a577d28c323800e5a402415c99c6ee5ac7b"

      def install
        bin.install "pipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/idestis/pipe/releases/download/v1.0.3/pipe-1.0.3-linux-amd64.tar.gz"
      sha256 "fe5a28748bc12eb8e1af4662f7f26dc2ccca625a5cf8f71b128a12d4a5625f16"
      def install
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idestis/pipe/releases/download/v1.0.3/pipe-1.0.3-linux-arm64.tar.gz"
      sha256 "10cee49de1f89d97c8aba71959a74a0aae35428b6ab68347e2acd645255bb5dc"
      def install
        bin.install "pipe"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pipe --version")
  end
end
