# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipe < Formula
  desc "CI-friendly pipeline runner inspired by Taskfile"
  homepage "https://github.com/getpipe-dev/pipe"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.1.0/pipe-2.1.0-darwin-amd64.tar.gz"
      sha256 "01bd6180d5d83b9d933c3c1b3a0a068b1e90285ebdb0b5e4ebacdb70c8e45b35"

      def install
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.1.0/pipe-2.1.0-darwin-arm64.tar.gz"
      sha256 "cd2d3816a515306d00c802de3fdefa51c3fa3735e572b1e6bcc5becfc4b16ab3"

      def install
        bin.install "pipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.1.0/pipe-2.1.0-linux-amd64.tar.gz"
      sha256 "c47a8534abfdceee74075ea914eb1d226c83115c59f5dd0f4786cf7404331140"
      def install
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.1.0/pipe-2.1.0-linux-arm64.tar.gz"
      sha256 "a63ac20561193ad63fe161d7efbd0175647e813089d528c999c3a839672b66f6"
      def install
        bin.install "pipe"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pipe --version")
  end
end
