# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pipe < Formula
  desc "CI-friendly pipeline runner inspired by Taskfile"
  homepage "https://github.com/getpipe-dev/pipe"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.4.0/pipe-2.4.0-darwin-amd64.tar.gz"
      sha256 "eed97bba288ad60be5181b378ea432d39161325b08e14aa45be41fb96500ea80"

      define_method(:install) do
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.4.0/pipe-2.4.0-darwin-arm64.tar.gz"
      sha256 "57c7267227398f25664d793fdafcd2d61adb94a9248601622d4810b48ec6b42d"

      define_method(:install) do
        bin.install "pipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.4.0/pipe-2.4.0-linux-amd64.tar.gz"
      sha256 "0c53fc86f85c59c419a843afbd19e9d9883b0f89e7a65f68fb36fba278aa785d"
      define_method(:install) do
        bin.install "pipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getpipe-dev/pipe/releases/download/v2.4.0/pipe-2.4.0-linux-arm64.tar.gz"
      sha256 "1d86dcb51ce464d466adc835a39fbc843827214917ad02bac2d23e2c3765d057"
      define_method(:install) do
        bin.install "pipe"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pipe --version")
  end
end
